# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a68f4f6a1f144e3a0c29649f653efee86d73e231f01b173763703fa1c855327f51537afcec89a3745948cc5cface390f3e6e1369efb4ec81e9f00d6090a2a7

test:
  secret_key_base: 17379b3805277ef8ee6272712482674155ac4b785d4338b9b2d4f18b04f91a51ec17b62ed8bc89a077313e3e5c036d904afcc4fd9740833c30ae4c10013ac77f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
